services:
  creditcalculator.api:
    image: ${DOCKER_REGISTRY-}creditcalculatorapi
    container_name: creditcalculator.api
    build:
      context: .
      dockerfile: CreditCalculator.API/Dockerfile

  pgsql-db:
    image: postgres:15
    container_name: pgsql-db

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    depends_on:
      - pgsql-db
 
  creditcalculator.ui:
    image: ${DOCKER_REGISTRY-}creditcalculatorui
    container_name: creditcalculator-ui
    build: 
      context: credit-calculator-ui
      dockerfile: Dockerfile